services:
  - type: worker
    name: discord-bot  # ← имя сервиса в Render (можете изменить)
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python cbot/bot.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
